apiVersion: v2
name: kyverno-policies-dx
appVersion: master
description: Giant Swarm policies for DX management.
home: https://github.com/giantswarm/kyverno-policies-dx
annotations:
  io.giantswarm.application.team: honeybadger
version:
- - .Version
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
