apiVersion: v1
name: kyverno-policies-dx
appVersion: master
description: Giant Swarm policies for DX management.
home: https://github.com/giantswarm/kyverno-policies-dx
annotations:
  application.giantswarm.io/team: "honeybadger"
  config.giantswarm.io/version: 1.x.x
version: 0.8.2
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
